server:
  port: 8081

spring:
  application:
    name: document-service
  datasource:
    url: jdbc:postgresql://dpg-d997fncs728c73crljn0-a.oregon-postgres.render.com:5432/blocksign_docs?sslmode=require
    username: blocksign_user
    password: 7KTbsnTKchrW2KcNoKGnFqg8d6Pj1kEn
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
      minimum-idle: 1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
